### ISSUE TITLE
handle the error

### ISSUE THREAD

**Issue by devpato** [junejanean/react-blog#3]
https://github.com/junejanean/react-blog/blob/f13f2d28095213bb415ba84e5a3c1850df20c731/client/src/components/Pages/Home/Home.jsx#L26

create an error message in the screen if this fails

**Comment by junejanean** [comment]
Done. Screenshot attached with error when no posts are loaded.
![Screen Shot 2022-05-03 at 11 30 18 AM](https://user-images.githubusercontent.com/1850810/166507291-0a78fa90-3d28-4927-b118-091331567312.png)
