### ISSUE TITLE
Create separate css files

### ISSUE THREAD

**Issue by devpato** [junejanean/react-blog#5]
https://github.com/junejanean/react-blog/blob/f13f2d28095213bb415ba84e5a3c1850df20c731/client/src/styles.css#L1

-This is not correct, this file should only contain the global stylings
-each component should have its one CSS file. Example home.jsx should have home.css
-You will run into an issue when having separate CSS files and reusing same class name across components, meaning the CSS will leak into other components. Take a look at CSS modules to prevent this. Eg home.module.css

**Comment by junejanean** [comment]
Huh, I was wondering about this after seeing them in difference projects. It seemed tedious and redundant to have so many CSS files. I've worked on very large sites before and we've had 1-3 main css files. I thought that if the parent div of each component was named with a specific component class or id, that would solve the issue.

But if this is not standard practice, I will change it.

**Comment by junejanean** [comment]
Done.
